apiVersion: v1
kind: Service
metadata:
  name: mgauthsphere-service
  labels: 
    app: mgauthsphere-service

spec:
  type: ClusterIP
  selector:
    app: mgauthsphere-api
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000