# Generated by Django 4.2.1 on 2024-04-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_products_alter_mgrealm_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mgrealm',
            name='signed_services',
        ),
        migrations.AddField(
            model_name='mgrealm',
            name='signed_services',
            field=models.ManyToManyField(related_name='services', to='api.products'),
        ),
    ]
