# Generated by Django 4.2.1 on 2024-04-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_mgrealm_signed_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mgrealm',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='mgrealm',
            name='user_permissions',
        ),
    ]
