# Generated by Django 4.2.1 on 2024-04-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_mgrealm_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgrealm',
            name='api_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='mgrealm',
            name='signed_services',
        ),
        migrations.AddField(
            model_name='mgrealm',
            name='signed_services',
            field=models.CharField(default='MGRealm', max_length=50),
        ),
    ]
