# Generated by Django 4.2.1 on 2024-04-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0007_mgrealm_api_token_remove_mgrealm_signed_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgrealm',
            name='user_permissions',
            field=models.ManyToManyField(related_name='mguser_set', to='auth.permission'),
        ),
    ]
