# Generated by Django 4.2.1 on 2024-04-07 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_mgrealm_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mgrealm_sessions',
            name='session_data',
        ),
        migrations.AddField(
            model_name='mgrealm_sessions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
