# Generated by Django 4.2.1 on 2024-04-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_mgrealm_sessions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='expire_Date',
            field=models.DateField(db_index=True),
        ),
    ]
