# Generated by Django 4.2.1 on 2024-04-08 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_mgrealm_sessions_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 8, 23, 29, 3, 361013), editable=False),
        ),
    ]
