# Generated by Django 4.2.1 on 2024-04-09 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_products_mg_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgrealm',
            name='signed_services',
            field=models.ManyToManyField(related_name='signedservices', to='api.mg_products'),
        ),
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 22, 17, 45, 216605)),
        ),
    ]
