# Generated by Django 5.0.4 on 2024-06-25 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_mgrealm_signed_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mg_products',
            name='app_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 20, 11, 11, 694957)),
        ),
    ]
