# Generated by Django 5.0.4 on 2024-06-25 14:55

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_mg_products_app_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgrealm',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mgrealm',
            name='created_service',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mg_products',
            name='app_key',
            field=models.CharField(blank=True, max_length=50, verbose_name='App key (autogenerated)'),
        ),
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 25, 20, 25, 10, 57168)),
        ),
    ]
