# Generated by Django 5.0.4 on 2024-06-26 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_mgrealm_created_date_mgrealm_created_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mg_products',
            options={'verbose_name': 'MG Product', 'verbose_name_plural': 'MG Products'},
        ),
        migrations.AlterModelOptions(
            name='mgrealm',
            options={'verbose_name': 'User Account', 'verbose_name_plural': 'User Accounts'},
        ),
        migrations.AlterModelOptions(
            name='mgrealm_sessions',
            options={'verbose_name': 'Account Session', 'verbose_name_plural': 'Account Sessions'},
        ),
        migrations.RemoveField(
            model_name='mgrealm',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 22, 14, 9, 958783)),
        ),
    ]
