# Generated by Django 5.0.4 on 2024-06-26 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_mg_products_options_alter_mgrealm_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mgrealm',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 22, 56, 30, 193874)),
        ),
    ]
