# Generated by Django 5.0.4 on 2024-06-27 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_mgrealm_sessions_created_on'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mgrealm',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 12, 32, 47, 675471)),
        ),
    ]
