# Generated by Django 5.0.4 on 2024-07-09 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_mgrealm_sessions_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mgrealm',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='mgrealm',
            name='username',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 21, 27, 32, 618821)),
        ),
    ]
