# Generated by Django 5.0.4 on 2024-07-09 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_mgrealm_email_alter_mgrealm_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mgrealm',
            name='username',
        ),
        migrations.AlterField(
            model_name='mgrealm',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 21, 29, 31, 390869)),
        ),
    ]
