# Generated by Django 5.0.4 on 2024-07-09 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_mgrealm_username_alter_mgrealm_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mgrealm',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 9, 21, 34, 54, 574390)),
        ),
    ]
