# Generated by Django 5.0.4 on 2024-07-10 15:06

import api.modelmanager
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_mgrealm_sessions_created_on'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mgrealm',
            managers=[
                ('objects', api.modelmanager.CustomManager()),
            ],
        ),
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 20, 36, 5, 715266)),
        ),
    ]
