# Generated by Django 5.0.4 on 2024-07-10 15:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_mgrealm_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mgrealm',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 20, 47, 46, 345372)),
        ),
    ]
