# Generated by Django 5.0.4 on 2024-07-10 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_mgrealm_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 21, 56, 47, 316453)),
        ),
    ]
