# Generated by Django 5.0.4 on 2024-07-10 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_mgrealm_sessions_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 10, 22, 0, 5, 761811)),
        ),
    ]
