# Generated by Django 5.0.4 on 2024-09-04 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_rename_mg_id_mgrealm_userid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mgrealm_sessions",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 4, 17, 16, 25, 20091)
            ),
        ),
    ]
