# Generated by Django 5.0.4 on 2025-01-04 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_rename_mg_id_mgrealm_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mg_products',
            name='prvkey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mg_products',
            name='pubkey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mg_products',
            name='symkey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 4, 16, 13, 38, 213682)),
        ),
    ]
