# Generated by Django 5.0.4 on 2024-09-10 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_alter_mgrealm_sessions_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mgrealm_sessions",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 10, 12, 4, 8, 839851)
            ),
        ),
    ]
