# Generated by Django 5.0.4 on 2025-05-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_mgrealm_sessions_created_on'),
        ('api', '0040_mgrealm_is_oauth_mgrealm_oauth_credentials_and_more'),
    ]

    operations = [
    ]
