# Generated by Django 5.0.4 on 2025-05-09 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_merge_20250509_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgrealm',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 20, 3, 39, 203981)),
        ),
    ]
