# Generated by Django 5.0.4 on 2025-05-16 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_mgrealm_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mg_products',
            options={'verbose_name': 'MG Service Account', 'verbose_name_plural': 'MG Service Accounts'},
        ),
        migrations.AlterModelOptions(
            name='mgrealm_sessions',
            options={'verbose_name': 'User Account Session', 'verbose_name_plural': 'User Account Sessions'},
        ),
        migrations.AddField(
            model_name='mgrealm_sessions',
            name='last_session_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mgrealm',
            name='api_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='Developer Token'),
        ),
        migrations.AlterField(
            model_name='mgrealm_sessions',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 20, 57, 58, 92302)),
        ),
    ]
