name: Deploy pythonanywhere webapp
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Re-Deploy Pythonanywhere Django API
        uses: umuttopalak/pythonanywhere-deploy-action@master
        with:
          host: "www.pythonanywhere.com"
          username: "MGAuthSphere"
          api_token: "a77cf6fe7ea22678ce2e0c114fb853b4eeb05924"
          domain_name: "mgauthsphere.pythonanywhere.com"
          console_id:  "33267297"
          virtual_env: ".virtualenvs/env"
          directory: "MGAuthSphere"
